version: 0.2
env:
  variables:
      DEBUG_MCVINE_BUILD: 0
phases:
  install:
    commands:
      - free -h
      - df -h
      - mount
      - # apt-get update && apt-get install -y procps freeglut3-dev libglu1-mesa unzip
      - yum install -y mesa-libGLU-devel unzip time
      - pwd
      - ls -tl ./
      - which git
      - which python
      - echo $PYTHON_VERSION
      - echo $CODEBUILD_BUILD_NUMBER
      - export JOB_NAME=dgsres
      - export BUILD_NUMBER=$CODEBUILD_BUILD_NUMBER
      - ./builders/aws-codebuild/install-conda.sh
      - ./builders/aws-codebuild/install-deps.sh
  pre_build:
    commands:
      - echo PreBuild started on `date`
      - echo PreBuild ended on `date`
  build:
    commands:
      - echo Build started on `date`
      - ./builders/aws-codebuild/test.sh
      - df -h
      - echo Build ended on `date`
  post_build:
    commands:
      - echo PostBuild completed on `date`
      - echo PostBuild ended on `date`
artifacts:
  files:
